<?php
define('TEST_PATH', dirname(__FILE__).DIRECTORY_SEPARATOR);
define('ROOT_PATH', TEST_PATH.'fixture'.DIRECTORY_SEPARATOR);
define('CACHE_PATH', ROOT_PATH.'cache'.DIRECTORY_SEPARATOR);
require dirname(TEST_PATH).DIRECTORY_SEPARATOR
  .'lib'.DIRECTORY_SEPARATOR.'ClassLoader.php';